runtime: go
api_version: go1
instance_class: F1
service: default
automatic_scaling:
env_variables:
  GA_TRACKING_ID: {{.GA_TRACKING_ID}}

handlers:
- url: /static
  static_dir: static
- url: /robots.txt
  static_files: templates/robots.txt
- url: /.*
  script: _go_app
